server:
  port: ${SERVER_INTERNAL_PORT}

spring:
  application:
    name: server-ports-manager
  aop:
    auto: true
    proxy-target-class: true

database:
  url: ${DB_URL}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  schema: public

config:
  jwt:
    secret: ${JWT_SECRET}
    access_token_expiration: ${JWT_ACCESS_EXPIRATION_TIME}
    refresh_token_expiration: ${JWT_REFRESH_EXPIRATION_TIME}