CREATE TABLE ports_storage
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    port_number BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_ports_storage PRIMARY KEY (id)
);

ALTER TABLE ports_storage
    ADD CONSTRAINT uc_ports_storage_portnumber UNIQUE (port_number);

ALTER TABLE ports_storage
    ADD CONSTRAINT FK_PORTS_STORAGE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);